//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZRetailer.ZWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZWS.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ZRetailer.ZWS.HelloWorldResponse HelloWorld(ZRetailer.ZWS.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldWithArguement", ReplyAction="*")]
        ZRetailer.ZWS.HelloWorldWithArguementResponse HelloWorldWithArguement(ZRetailer.ZWS.HelloWorldWithArguementRequest request);
        
        // CODEGEN: Generating message contract since element name SettingName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckSettingsValue", ReplyAction="*")]
        ZRetailer.ZWS.CheckSettingsValueResponse CheckSettingsValue(ZRetailer.ZWS.CheckSettingsValueRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ZRetailer.ZWS.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ZRetailer.ZWS.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZRetailer.ZWS.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ZRetailer.ZWS.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldWithArguementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldWithArguement", Namespace="http://tempuri.org/", Order=0)]
        public ZRetailer.ZWS.HelloWorldWithArguementRequestBody Body;
        
        public HelloWorldWithArguementRequest() {
        }
        
        public HelloWorldWithArguementRequest(ZRetailer.ZWS.HelloWorldWithArguementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldWithArguementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        public HelloWorldWithArguementRequestBody() {
        }
        
        public HelloWorldWithArguementRequestBody(string Name) {
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldWithArguementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldWithArguementResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZRetailer.ZWS.HelloWorldWithArguementResponseBody Body;
        
        public HelloWorldWithArguementResponse() {
        }
        
        public HelloWorldWithArguementResponse(ZRetailer.ZWS.HelloWorldWithArguementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldWithArguementResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldWithArguementResult;
        
        public HelloWorldWithArguementResponseBody() {
        }
        
        public HelloWorldWithArguementResponseBody(string HelloWorldWithArguementResult) {
            this.HelloWorldWithArguementResult = HelloWorldWithArguementResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckSettingsValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckSettingsValue", Namespace="http://tempuri.org/", Order=0)]
        public ZRetailer.ZWS.CheckSettingsValueRequestBody Body;
        
        public CheckSettingsValueRequest() {
        }
        
        public CheckSettingsValueRequest(ZRetailer.ZWS.CheckSettingsValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckSettingsValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SettingName;
        
        public CheckSettingsValueRequestBody() {
        }
        
        public CheckSettingsValueRequestBody(string SettingName) {
            this.SettingName = SettingName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckSettingsValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckSettingsValueResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZRetailer.ZWS.CheckSettingsValueResponseBody Body;
        
        public CheckSettingsValueResponse() {
        }
        
        public CheckSettingsValueResponse(ZRetailer.ZWS.CheckSettingsValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckSettingsValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckSettingsValueResult;
        
        public CheckSettingsValueResponseBody() {
        }
        
        public CheckSettingsValueResponseBody(string CheckSettingsValueResult) {
            this.CheckSettingsValueResult = CheckSettingsValueResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : ZRetailer.ZWS.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<ZRetailer.ZWS.Service1Soap>, ZRetailer.ZWS.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZRetailer.ZWS.HelloWorldResponse ZRetailer.ZWS.Service1Soap.HelloWorld(ZRetailer.ZWS.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ZRetailer.ZWS.HelloWorldRequest inValue = new ZRetailer.ZWS.HelloWorldRequest();
            inValue.Body = new ZRetailer.ZWS.HelloWorldRequestBody();
            ZRetailer.ZWS.HelloWorldResponse retVal = ((ZRetailer.ZWS.Service1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZRetailer.ZWS.HelloWorldWithArguementResponse ZRetailer.ZWS.Service1Soap.HelloWorldWithArguement(ZRetailer.ZWS.HelloWorldWithArguementRequest request) {
            return base.Channel.HelloWorldWithArguement(request);
        }
        
        public string HelloWorldWithArguement(string Name) {
            ZRetailer.ZWS.HelloWorldWithArguementRequest inValue = new ZRetailer.ZWS.HelloWorldWithArguementRequest();
            inValue.Body = new ZRetailer.ZWS.HelloWorldWithArguementRequestBody();
            inValue.Body.Name = Name;
            ZRetailer.ZWS.HelloWorldWithArguementResponse retVal = ((ZRetailer.ZWS.Service1Soap)(this)).HelloWorldWithArguement(inValue);
            return retVal.Body.HelloWorldWithArguementResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZRetailer.ZWS.CheckSettingsValueResponse ZRetailer.ZWS.Service1Soap.CheckSettingsValue(ZRetailer.ZWS.CheckSettingsValueRequest request) {
            return base.Channel.CheckSettingsValue(request);
        }
        
        public string CheckSettingsValue(string SettingName) {
            ZRetailer.ZWS.CheckSettingsValueRequest inValue = new ZRetailer.ZWS.CheckSettingsValueRequest();
            inValue.Body = new ZRetailer.ZWS.CheckSettingsValueRequestBody();
            inValue.Body.SettingName = SettingName;
            ZRetailer.ZWS.CheckSettingsValueResponse retVal = ((ZRetailer.ZWS.Service1Soap)(this)).CheckSettingsValue(inValue);
            return retVal.Body.CheckSettingsValueResult;
        }
    }
}
